
on:
  push:
  public:
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
     - name: MegaLinter
       uses: oxsecurity/megalinter@v6.18.0
     
        
         
